---
apiVersion: v1
kind: Pod
metadata:
  name: persistent-volume-optimizer
spec:
  serviceAccountName: pod-enable
  containers:
   - name: application-pod
     image: nginx:latest
     command:
        - "/bin/sh"
        - "-c"
        - while true; do echo "bhagya" >> /mnt/vpcdisk/vpcfile; sleep 1; echo "Gaurav" >> /mnt/cosdisk/cosfile; sleep 1; done
     volumeMounts:
       - mountPath: /mnt/vpcdisk
         name: vpcdisk
       - mountPath: /mnt/cosdisk
         name: cosdisk

   - name: persistent-volume-optimizer-pod
     image: bhagyak1/optimizer:27
     env:
       - name: CMNAME
         value: "pvc-optimizer-01"
       - name: POD_NAMESPACE
         value: "default"
     volumeMounts:
       - mountPath: /mnt/vpcdisk
         name: vpcdisk
       - mountPath: /mnt/cosdisk
         name: cosdisk
  volumes:
   - name: vpcdisk
     persistentVolumeClaim:
       claimName: pvc1
   - name: cosdisk
     persistentVolumeClaim:
       claimName: pvc2
